name: Docker Publish

# Prevent two instances of this workflow running at the same time
concurrency: docker-publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: meyfa
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./client/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags:  meyfa/ddns-client:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # See: https://docs.docker.com/build/ci/github-actions/update-dockerhub-desc/
      - name: Update DockerHub description
        uses: peter-evans/dockerhub-description@432a30c9e07499fd01da9f8a49f0faf9e0ca5b77 # v4.0.2
        with:
          username: meyfa
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          repository: meyfa/ddns-client
          short-description: ${{ github.event.repository.description }}
          enable-url-completion: true
